name: home
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.4+5
  fluttertoast: ^3.1.3
  http: ^0.12.0+2
  connectivity: ^0.4.5+6
  rxdart: ^0.22.6
  permission_handler: ^3.2.0
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  provider: ^4.0.2
  image_picker: ^0.6.3+1
  keyboard_avoider: ^0.1.2
  firebase_messaging: ^6.0.12
  device_info: ^0.4.2+2
  country_pickers: ^1.3.0
  flutter_html: ^0.8.2
  intl: ^0.16.1
  url_launcher: ^5.4.11
  webview_flutter: #^0.3.4
    git:
      url: git://github.com/jaumard/plugins
      ref: feature/webview_transparency
      path: packages/webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: PoppinsBlackItalic
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: PoppinsExtraLightItalic
      fonts:
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsLightItalic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
        - asset: assets/fonts/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: PoppinsThinItalic
      fonts:
        - asset: assets/fonts/Poppins-ThinItalic.ttf

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
